[theme]
base="dark"
primaryColor="#483d8b"

[client]
toolbarMode="viewer"

[theme.sidebar]
primaryColor="black"
backgroundColor="black"

[server]
enableCORS=false
enableXsrfProtection=false
headless=true
